package ResImpl;

public enum CrashType
{
	BEFORE_VOTE_REQUEST, AFTER_REQUEST_BEFORE_VOTE_RETURN, AFTER_VOTE_RETURN_BEFORE_COMMIT_REQUEST,
	AFTER_SENDING_ANSWER, AFTER_DECISION_BEFORE_COMMIT, TM_BEFORE_REPLIES, TM_SOME_REPLIES, TM_BEFORE_DECISION,
	TM_BEFORE_DECISION_SENT, TM_SOME_DECISIONS_SENT, TM_ALL_DECISIONS_SENT
}
